"""
TrenchBroom Python API
"""
from __future__ import annotations
from _frozen_importlib import BuiltinImporter as __loader__
import collections.abc
import typing
import typing_extensions
from . import actions
from . import assets
from . import brushes
from . import documents
from . import entities
from . import faces
from . import geometry
from . import groups
from . import history
from . import materials
from . import objects
from . import validation
from . import viewport
__all__: list[str] = ['Brush', 'Document', 'Entity', 'Face', 'Material', 'MaterialCollection', 'Plane', 'PluginPanel', 'Selection', 'Transaction', 'Vec3', 'actions', 'assets', 'brushes', 'clear_interval', 'create_plugin_panel', 'documents', 'entities', 'faces', 'geometry', 'groups', 'history', 'materials', 'objects', 'register_callback', 'set_interval', 'set_timeout', 'unregister_callback', 'validation', 'viewport']
class Brush:
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def faces(self) -> list[Face]:
        ...
    @property
    def entity(self) -> Entity:
        ...
    @property
    def id(self) -> str:
        ...
class Document:
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def clear_selection(self) -> None:
        ...
    def close(self, discard_changes: bool = False) -> None:
        ...
    def export(self, path: str, strip_tb_properties: bool = True) -> None:
        ...
    def reload(self) -> None:
        ...
    def save(self) -> None:
        ...
    def save_as(self, path: str) -> None:
        ...
    def select(self, arg0: collections.abc.Iterable) -> None:
        ...
    def set_face_uvs(self, updates: collections.abc.Iterable) -> bool:
        ...
    def set_face_uvs_with_split(self, updates: collections.abc.Iterable) -> bool:
        ...
    def set_triangle_uvs(self, triangles: typing.Any) -> bool:
        ...
    def transaction(self, name: str = 'Python API Script') -> Transaction:
        ...
    def vertex_tool_vertices(self) -> list[Vec3]:
        ...
    @property
    def entities(self) -> list[Entity]:
        ...
    @property
    def id(self) -> str:
        ...
    @property
    def material_collections(self) -> list[MaterialCollection]:
        ...
    @property
    def materials(self) -> list[Material]:
        ...
    @property
    def path(self) -> typing.Any:
        ...
    @property
    def selection(self) -> Selection:
        ...
class Entity:
    def __contains__(self, arg0: str) -> bool:
        ...
    def __delitem__(self, arg0: str) -> None:
        ...
    def __getitem__(self, arg0: str) -> str:
        ...
    def __iter__(self) -> collections.abc.Iterator:
        ...
    def __len__(self) -> int:
        ...
    def __repr__(self) -> str:
        ...
    def __setitem__(self, arg0: str, arg1: str) -> None:
        ...
    def __str__(self) -> str:
        ...
    def get(self, key: str, default: typing.Any = None) -> typing.Any:
        ...
    def items(self) -> list[tuple[str, str]]:
        ...
    def keys(self) -> list[str]:
        ...
    def remove(self, key: str) -> None:
        ...
    def set(self, key: str, value: str) -> None:
        ...
    def values(self) -> list[str]:
        ...
    @property
    def brushes(self) -> list[Brush]:
        ...
    @property
    def classname(self) -> str:
        ...
    @property
    def id(self) -> str:
        ...
    @property
    def properties(self) -> dict:
        ...
class Face:
    material: str
    surface_contents: typing.Any
    surface_flags: typing.Any
    surface_value: typing.Any
    texture_name: str
    def __repr__(self) -> str:
        ...
    def __str__(self) -> str:
        ...
    def set_material(self, arg0: str) -> None:
        ...
    def set_uv_loops(self, loops: collections.abc.Iterable) -> bool:
        """
        Set all face vertices using texture pixel coordinates, not normalized UVs. Each item is {'vertex': index, 'uv': (u, v)}; supply every Face.vertices index. For a 256x128 texture, one full image spans (0, 0) to (256, 128). Returns False when the UV fit cannot be represented by the face mapping.
        """
    @property
    def id(self) -> str:
        ...
    @property
    def normal(self) -> tuple:
        ...
    @property
    def offset(self) -> tuple:
        ...
    @offset.setter
    def offset(self, arg1: typing.Any) -> None:
        ...
    @property
    def rotation(self) -> float:
        ...
    @rotation.setter
    def rotation(self, arg1: typing.SupportsFloat) -> None:
        ...
    @property
    def scale(self) -> tuple:
        ...
    @scale.setter
    def scale(self, arg1: typing.Any) -> None:
        ...
    @property
    def uv_loops(self) -> list:
        """
        Per-vertex texture pixel coordinates, not normalized UVs. Each item is {'vertex': index, 'uv': (u, v)}; indices address Face.vertices.
        """
    @property
    def vertices(self) -> list:
        ...
class Material:
    @property
    def collection_name(self) -> str:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def width(self) -> int:
        ...
class MaterialCollection:
    @property
    def material_count(self) -> int:
        ...
    @property
    def materials(self) -> list[Material]:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def path(self) -> str:
        ...
class Plane:
    normal: Vec3
    @staticmethod
    def from_points(arg0: Vec3, arg1: Vec3, arg2: Vec3) -> Plane:
        ...
    def __init__(self, arg0: Vec3, arg1: typing.SupportsFloat) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def distance(self, arg0: Vec3) -> float:
        ...
    def project(self, arg0: Vec3) -> Vec3:
        ...
    @property
    def dist(self) -> float:
        ...
    @dist.setter
    def dist(self, arg0: typing.SupportsFloat) -> None:
        ...
class PluginPanel:
    def add_button(self, arg0: str, arg1: typing.Any) -> None:
        ...
    def add_button_callback(self, arg0: str, arg1: typing.Any) -> None:
        ...
    @typing.overload
    def add_checkbox(self, arg0: str, arg1: bool, arg2: typing.Any) -> None:
        ...
    @typing.overload
    def add_checkbox(self, arg0: str, arg1: str, arg2: bool) -> None:
        ...
    def add_color_field(self, arg0: str, arg1: str, arg2: typing.Any) -> None:
        ...
    def add_column(self, arg0: str) -> PluginPanel:
        ...
    @typing.overload
    def add_combo_box(self, arg0: collections.abc.Sequence[str], arg1: typing.SupportsInt, arg2: typing.Any) -> None:
        ...
    @typing.overload
    def add_combo_box(self, key: str, label: str, items: collections.abc.Sequence[str], callback: typing.Any = None, current: typing.Any = None) -> None:
        ...
    def add_float_field(self, key: str, label: str, value: typing.SupportsFloat = 0.0, min: typing.SupportsFloat = -1000000.0, max: typing.SupportsFloat = 1000000.0, decimals: typing.SupportsInt = 2, step: typing.SupportsFloat = 1.0) -> None:
        ...
    def add_group(self, arg0: str, arg1: str) -> PluginPanel:
        ...
    def add_html_view(self, key: str, html: str, height: typing.SupportsInt = 200, callback: typing.Any = None) -> None:
        ...
    def add_int_field(self, key: str, label: str, value: typing.SupportsInt = 0, min: typing.SupportsInt = -2147483648, max: typing.SupportsInt = 2147483647) -> None:
        ...
    def add_label(self, arg0: str) -> None:
        ...
    def add_label_named(self, arg0: str, arg1: str) -> None:
        ...
    def add_line_edit(self, arg0: str, arg1: typing.Any) -> None:
        ...
    def add_row(self, arg0: str) -> PluginPanel:
        ...
    def add_table_widget(self, key: str, columns: collections.abc.Sequence[str], rows: collections.abc.Sequence[collections.abc.Sequence[str]], height: typing.SupportsInt = 200, callback: typing.Any = None) -> None:
        ...
    def add_text_area(self, key: str, label: str, value: str = '', height: typing.SupportsInt = 120, placeholder: str = '') -> None:
        ...
    def add_text_field(self, key: str, label: str, value: str = '', placeholder: str = '') -> None:
        ...
    def add_tree_widget(self, key: str, columns: collections.abc.Sequence[str], rows: collections.abc.Sequence[collections.abc.Sequence[str]], height: typing.SupportsInt = 200, callback: typing.Any = None) -> None:
        ...
    def clear(self) -> None:
        ...
    def get_checkbox(self, arg0: str) -> bool:
        ...
    def get_color_field(self, arg0: str) -> tuple:
        ...
    def get_combo_box_text(self, arg0: str) -> str:
        ...
    def get_float_field(self, arg0: str) -> float:
        ...
    def get_int_field(self, arg0: str) -> int:
        ...
    def get_text_area(self, arg0: str) -> str:
        ...
    def get_text_field(self, arg0: str) -> str:
        ...
    def set_html_view(self, arg0: str, arg1: str) -> None:
        ...
    def set_label_text(self, arg0: str, arg1: str) -> None:
        ...
    def set_table_widget_rows(self, arg0: str, arg1: collections.abc.Sequence[collections.abc.Sequence[str]]) -> None:
        ...
    def set_text_area(self, arg0: str, arg1: str) -> None:
        ...
    def set_text_field(self, arg0: str, arg1: str) -> None:
        ...
    def set_tree_widget_items(self, arg0: str, arg1: collections.abc.Sequence[collections.abc.Sequence[str]]) -> None:
        ...
    def set_widget_visible(self, arg0: str, arg1: bool) -> None:
        ...
class Selection:
    def __contains__(self, arg0: str) -> bool:
        ...
    def __getitem__(self, arg0: str) -> str:
        ...
    def __repr__(self) -> str:
        ...
    def __setitem__(self, arg0: str, arg1: str) -> None:
        ...
    def __str__(self) -> str:
        ...
    def add(self, arg0: collections.abc.Iterable) -> bool:
        ...
    def bounds(self) -> typing.Any:
        ...
    def brush_vertices(self) -> list[list[Vec3]]:
        ...
    def chamfer_edges(self, distance: typing.SupportsFloat, segments: typing.SupportsInt = 1) -> bool:
        ...
    def chamfer_vertices(self, distance: typing.SupportsFloat) -> bool:
        ...
    def clear(self) -> bool:
        ...
    def deselect_all(self) -> bool:
        ...
    def duplicate(self) -> bool:
        ...
    def inspect(self) -> dict:
        ...
    def rotate(self, axis: typing.Any, angle_degrees: typing.SupportsFloat, *, center: typing.Any = None) -> bool:
        """
        Rotate the current selection around an axis in degrees. center defaults to selection bounds.
        """
    def scale(self, factors: typing.Any, *, center: typing.Any = None) -> bool:
        """
        Scale the current selection by a scalar or map-unit Vec3. center defaults to selection bounds.
        """
    def set(self, arg0: collections.abc.Iterable) -> bool:
        ...
    def set_property(self, key: str, value: str, create_if_missing: bool = True) -> bool:
        ...
    def translate(self, offset: typing.Any) -> bool:
        """
        Translate the current selection by a map-unit Vec3.
        """
    def triangle_uvs(self) -> dict:
        ...
    @property
    def all_entities(self) -> list[Entity]:
        ...
    @property
    def brush(self) -> typing.Any:
        ...
    @property
    def brush_faces(self) -> list[Face]:
        ...
    @property
    def brushes(self) -> list[Brush]:
        ...
    @property
    def classname(self) -> typing.Any:
        ...
    @property
    def entities(self) -> list[Entity]:
        ...
    @property
    def entity(self) -> typing.Any:
        ...
    @property
    def properties(self) -> typing.Any:
        ...
class Transaction:
    def __enter__(self) -> Transaction:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> bool:
        ...
    def cancel(self) -> None:
        ...
    def commit(self) -> bool:
        ...
class Vec3:
    def __add__(self, arg0: Vec3) -> Vec3:
        ...
    def __init__(self, arg0: typing.SupportsFloat, arg1: typing.SupportsFloat, arg2: typing.SupportsFloat) -> None:
        ...
    def __iter__(self) -> collections.abc.Iterator:
        ...
    def __mul__(self, arg0: typing.SupportsFloat) -> Vec3:
        ...
    def __repr__(self) -> str:
        ...
    def __rmul__(self, arg0: typing.SupportsFloat) -> Vec3:
        ...
    def __sub__(self, arg0: Vec3) -> Vec3:
        ...
    def __truediv__(self, arg0: typing.SupportsFloat) -> Vec3:
        ...
    def cross(self, arg0: Vec3) -> Vec3:
        ...
    def dot(self, arg0: Vec3) -> float:
        ...
    def length(self) -> float:
        ...
    def normalize(self) -> Vec3:
        ...
    def normalized(self) -> Vec3:
        ...
    @property
    def x(self) -> float:
        ...
    @x.setter
    def x(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def y(self) -> float:
        ...
    @y.setter
    def y(self, arg0: typing.SupportsFloat) -> None:
        ...
    @property
    def z(self) -> float:
        ...
    @z.setter
    def z(self, arg0: typing.SupportsFloat) -> None:
        ...
def _cleanup_plugin(arg0: str) -> None:
    ...
def _cleanup_plugin_session(arg0: typing_extensions.CapsuleType) -> None:
    ...
def _emit_event(arg0: str) -> None:
    ...
def _has_event_callbacks(arg0: str) -> bool:
    ...
def _invalidate_document(arg0: typing_extensions.CapsuleType) -> None:
    ...
def clear_interval(arg0: typing.SupportsInt) -> None:
    ...
def create_plugin_panel(arg0: str) -> PluginPanel:
    ...
def register_callback(arg0: str, arg1: typing.Any) -> int:
    ...
def set_interval(arg0: typing.Any, arg1: typing.SupportsInt) -> int:
    ...
def set_timeout(arg0: typing.Any, arg1: typing.SupportsInt) -> int:
    ...
def unregister_callback(arg0: typing.SupportsInt) -> None:
    ...
_api_catalog: dict = {'trenchbroom': ['Vec3', 'Plane', 'Document', 'Selection', 'Entity', 'Brush', 'Face', 'Material', 'MaterialCollection', 'Transaction', 'PluginPanel', 'documents', 'objects', 'entities', 'brushes', 'faces', 'materials', 'groups', 'geometry', 'history', 'assets', 'actions', 'validation', 'viewport', 'create_plugin_panel', 'register_callback', 'unregister_callback', 'set_interval', 'clear_interval', 'set_timeout'], 'documents': ['current', 'list', 'snapshot', 'open', 'activate', 'close', 'save', 'save_as', 'export'], 'objects': ['translate', 'rotate', 'scale', 'duplicate', 'delete'], 'entities': ['list', 'selected', 'create', 'create_from_schema_batch', 'definitions', 'schema', 'link_chain_inspect', 'create_from_schema', 'tie_brushes', 'untie_brushes', 'delete', 'update', 'update_many', 'find'], 'brushes': ['list', 'selected', 'create', 'create_box', 'create_boxes', 'create_prism', 'create_prisms'], 'faces': ['list', 'selected', 'set_material'], 'materials': ['list', 'collections', 'search', 'current', 'apply', 'apply_by_filter', 'lock_get', 'lock_set', 'align_face', 'copy_from_face', 'replace'], 'groups': ['create_from_selection', 'inspect_selected', 'rename_selected', 'ungroup_selected'], 'geometry': ['analyze_selection', 'csg_selection'], 'history': ['status', 'undo', 'redo'], 'assets': ['search', 'place_model', 'place_sprite', 'place_sound'], 'actions': ['list', 'execute'], 'validation': ['check'], 'viewport': ['state', 'set_options', 'set_camera', 'focus_selection'], 'Vec3': ['x', 'y', 'z', 'dot', 'cross', 'length', 'normalize', 'normalized'], 'Plane': ['normal', 'dist', 'from_points', 'distance', 'project'], 'Document': ['id', 'path', 'entities', 'selection', 'materials', 'material_collections', 'vertex_tool_vertices', 'save', 'close', 'save_as', 'export', 'reload', 'transaction', 'set_triangle_uvs', 'set_face_uvs', 'set_face_uvs_with_split', 'select', 'clear_selection'], 'Selection': ['entity', 'brush', 'properties', 'classname', 'entities', 'all_entities', 'brushes', 'brush_faces', 'set_property', 'brush_vertices', 'triangle_uvs', 'bounds', 'inspect', 'set', 'add', 'deselect_all', 'clear', 'duplicate', 'translate', 'rotate', 'scale', 'chamfer_vertices', 'chamfer_edges'], 'Entity': ['id', 'classname', 'brushes', 'properties', 'keys', 'values', 'items', 'get', 'set', 'remove'], 'Brush': ['id', 'entity', 'faces'], 'Face': ['id', 'normal', 'vertices', 'uv_loops', 'texture_name', 'material', 'offset', 'scale', 'rotation', 'surface_contents', 'surface_flags', 'surface_value', 'set_uv_loops', 'set_material'], 'Material': ['name', 'collection_name', 'width', 'height'], 'MaterialCollection': ['name', 'path', 'material_count', 'materials'], 'Transaction': ['commit', 'cancel'], 'PluginPanel': ['add_label', 'add_label_named', 'set_label_text', 'add_group', 'add_row', 'add_column', 'set_widget_visible', 'add_button', 'add_button_callback', 'add_checkbox', 'get_checkbox', 'add_line_edit', 'add_text_field', 'get_text_field', 'set_text_field', 'add_text_area', 'get_text_area', 'set_text_area', 'add_int_field', 'get_int_field', 'add_float_field', 'get_float_field', 'add_combo_box', 'get_combo_box_text', 'add_color_field', 'get_color_field', 'add_table_widget', 'set_table_widget_rows', 'add_tree_widget', 'set_tree_widget_items', 'add_html_view', 'set_html_view', 'clear']}
