"""
Material collection operations.
"""
from __future__ import annotations
import trenchbroom
import typing
__all__: list[str] = ['align_face', 'apply', 'apply_by_filter', 'collections', 'copy_from_face', 'current', 'list', 'lock_get', 'lock_set', 'replace', 'search']
def align_face(faces: collections.abc.Iterable, mode: str) -> int:
    ...
def apply(faces: collections.abc.Iterable, material: str) -> int:
    ...
def apply_by_filter(brushes: collections.abc.Iterable, material: str, face_semantic: str = 'all', normal: typing.Any = None, normal_tolerance: typing.SupportsFloat = 0.75) -> int:
    ...
def collections() -> list[trenchbroom.MaterialCollection]:
    ...
def copy_from_face(source: trenchbroom.Face, targets: collections.abc.Iterable) -> int:
    ...
def current() -> str:
    ...
def list() -> list[trenchbroom.Material]:
    ...
def lock_get() -> dict:
    ...
def lock_set(texture_lock: typing.Any = None, uv_lock: typing.Any = None) -> dict:
    ...
def replace(find: str, replace: str, scope: str = 'selection') -> int:
    ...
def search(query: str, limit: typing.SupportsInt = 50) -> list[trenchbroom.Material]:
    ...
