param(
  [string] $ServerName = "trenchbroom",
  [string] $OutputDir = "",
  [switch] $Print
)

$ErrorActionPreference = "Stop"

function ConvertTo-PrettyJson {
  param([object] $Value)

  return $Value | ConvertTo-Json -Depth 64
}

function Escape-TomlString {
  param([string] $Value)

  return $Value.Replace("\", "\\").Replace('"', '\"')
}

$configPath = Join-Path $env:APPDATA "TrenchBroom\MCP\config.json"
if (-not (Test-Path $configPath)) {
  throw "MCP config not found: $configPath. Start TrenchBroom once and open Preferences > MCP."
}

$config = Get-Content -Path $configPath -Raw | ConvertFrom-Json
$hostName = if ([string]::IsNullOrWhiteSpace($config.httpHost)) { "127.0.0.1" } else { $config.httpHost }
$port = if ($null -eq $config.httpPort) { 37666 } else { $config.httpPort }

$url = "http://$hostName`:$port/mcp"

if ([string]::IsNullOrWhiteSpace($OutputDir)) {
  $OutputDir = Join-Path "build-release-codex" "mcp-config"
}

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
$resolvedOutputDir = (Resolve-Path $OutputDir).Path

$mcpServer = [ordered] @{
  type = "http"
  url = $url
}

$mcpServers = [ordered] @{
  mcpServers = [ordered] @{
    $ServerName = $mcpServer
  }
}

$genericConfig = [ordered] @{
  name = $ServerName
  type = "http"
  url = $url
  notes = @(
    "Start TrenchBroom first.",
    "Enable MCP in Preferences > MCP and use ReadOnly or Edit mode.",
    "Run scripts\\mcp-call.ps1 -Tool tb_inspect -ArgumentsJson '{\"view\":\"status\"}' to verify the local HTTP endpoint."
  )
}

$codexToml = @"
[mcp_servers.$ServerName]
type = "http"
url = "$(Escape-TomlString $url)"
"@

$genericPath = Join-Path $resolvedOutputDir "trenchbroom-mcp.http.json"
$mcpServersPath = Join-Path $resolvedOutputDir "trenchbroom-mcp.mcpServers.json"
$codexPath = Join-Path $resolvedOutputDir "trenchbroom-mcp.codex.toml"
$readmePath = Join-Path $resolvedOutputDir "README.md"

Set-Content -Path $genericPath -Value (ConvertTo-PrettyJson $genericConfig)
Set-Content -Path $mcpServersPath -Value (ConvertTo-PrettyJson $mcpServers)
Set-Content -Path $codexPath -Value $codexToml

$readme = @"
# TrenchBroom MCP Client Config

Generated by `scripts\mcp-config.ps1`.

## Server

Name: `$ServerName`

URL:

```text
$url
```

## Claude Code

```powershell
claude mcp remove $ServerName -s user
claude mcp add --scope user --transport http $ServerName $url
```

## Codex

```powershell
codex mcp add $ServerName --url $url
```

## Before Connecting

1. Start TrenchBroom.
2. Open `Preferences > MCP`.
3. Use `ReadOnly` for inspection or `Edit` for map-changing tools.
4. Run:

```powershell
scripts\mcp-call.ps1 -Tool tb_inspect -ArgumentsJson '{"view":"status"}'
```

If the smoke script reports `Forbidden`, TrenchBroom MCP mode is still `Off`.

## Compatibility

`trenchbroom-mcp.exe` is now only a legacy stdio shim. Prefer the HTTP URL above for Claude Code.
"@

Set-Content -Path $readmePath -Value $readme

Write-Host "MCP HTTP URL: $url"
Write-Host "Output directory: $resolvedOutputDir"
Write-Host "Generated:"
Write-Host "  $genericPath"
Write-Host "  $mcpServersPath"
Write-Host "  $codexPath"
Write-Host "  $readmePath"

if ($Print) {
  Write-Host ""
  Write-Host "Claude Code command:"
  Write-Host "claude mcp remove $ServerName -s user"
  Write-Host "claude mcp add --scope user --transport http $ServerName $url"
  Write-Host ""
  Write-Host "Codex command:"
  Write-Host "codex mcp add $ServerName --url $url"
  Write-Host ""
  Write-Host "mcpServers JSON:"
  Get-Content -Path $mcpServersPath
  Write-Host ""
  Write-Host "Codex TOML:"
  Get-Content -Path $codexPath
}
